/** Auto-generated from OWASP MASWE + MASTG Android tests-beta. Do not edit by hand. */
export const MAS_PROFILE_IDS = ['L1', 'L2', 'R', 'P'];
export const MAS_PROFILE_META = {
  L1: { id: 'MAS-L1', label: 'MAS-L1', title: 'Essential Security' },
  L2: { id: 'MAS-L2', label: 'MAS-L2', title: 'Advanced Security' },
  R: { id: 'MAS-R', label: 'MAS-R', title: 'Resilience' },
  P: { id: 'MAS-P', label: 'MAS-P', title: 'Privacy' },
};
/** @type {Record<string, string[]>} MASWE id → official profiles (L1/L2/R/P/EUDIW) */
export const MASWE_PROFILES = {
  "MASWE-0001": ["L2", "EUDIW"],
  "MASWE-0002": ["L1", "L2", "EUDIW"],
  "MASWE-0003": ["L1", "L2", "EUDIW"],
  "MASWE-0004": ["L1", "L2", "EUDIW"],
  "MASWE-0005": ["L1", "L2", "EUDIW"],
  "MASWE-0006": ["L1", "L2", "EUDIW"],
  "MASWE-0007": ["L1", "L2", "EUDIW"],
  "MASWE-0008": ["L1", "L2", "EUDIW"],
  "MASWE-0009": ["L1", "L2", "EUDIW"],
  "MASWE-0010": ["L1", "L2", "EUDIW"],
  "MASWE-0011": ["L1", "L2", "EUDIW"],
  "MASWE-0012": ["L1", "L2", "EUDIW"],
  "MASWE-0013": ["L1", "L2", "EUDIW"],
  "MASWE-0014": ["L1", "L2", "EUDIW"],
  "MASWE-0015": ["L2", "EUDIW"],
  "MASWE-0016": ["L2", "EUDIW"],
  "MASWE-0017": ["L2", "EUDIW"],
  "MASWE-0018": ["L1", "L2", "EUDIW"],
  "MASWE-0019": ["L1", "L2", "EUDIW"],
  "MASWE-0020": ["L2", "EUDIW"],
  "MASWE-0021": ["L2", "EUDIW"],
  "MASWE-0022": ["L2", "EUDIW"],
  "MASWE-0023": ["L2", "EUDIW"],
  "MASWE-0024": ["L2", "EUDIW"],
  "MASWE-0025": ["L2", "EUDIW"],
  "MASWE-0026": ["L1", "L2", "EUDIW"],
  "MASWE-0027": ["L1", "L2", "EUDIW"],
  "MASWE-0028": ["L2", "EUDIW"],
  "MASWE-0029": ["L1", "L2", "EUDIW"],
  "MASWE-0030": ["L1", "L2", "EUDIW"],
  "MASWE-0031": ["L1", "L2", "EUDIW"],
  "MASWE-0032": ["L1", "L2", "EUDIW"],
  "MASWE-0033": ["L1", "L2", "EUDIW"],
  "MASWE-0034": ["L1", "L2", "EUDIW"],
  "MASWE-0035": ["L1", "L2", "EUDIW"],
  "MASWE-0036": ["L2", "EUDIW"],
  "MASWE-0037": ["L2", "EUDIW"],
  "MASWE-0038": ["L2", "EUDIW"],
  "MASWE-0039": ["L2", "EUDIW"],
  "MASWE-0040": ["L2", "EUDIW"],
  "MASWE-0041": ["L2", "EUDIW"],
  "MASWE-0042": ["L1", "L2", "EUDIW"],
  "MASWE-0043": ["L2", "EUDIW"],
  "MASWE-0044": ["L1", "L2", "EUDIW"],
  "MASWE-0045": ["L2", "EUDIW"],
  "MASWE-0046": ["L2", "EUDIW"],
  "MASWE-0047": ["L1", "L2", "EUDIW"],
  "MASWE-0048": ["L1", "L2", "EUDIW"],
  "MASWE-0049": ["L2", "EUDIW"],
  "MASWE-0050": ["L1", "L2", "EUDIW"],
  "MASWE-0051": ["R", "EUDIW"],
  "MASWE-0052": ["R", "EUDIW"],
  "MASWE-0053": ["R", "EUDIW"],
  "MASWE-0054": ["R", "EUDIW"],
  "MASWE-0055": ["R", "EUDIW"],
  "MASWE-0056": ["R", "EUDIW"],
  "MASWE-0057": ["R", "EUDIW"],
  "MASWE-0058": ["R", "EUDIW"],
  "MASWE-0059": ["R", "EUDIW"],
  "MASWE-0060": ["R", "EUDIW"],
  "MASWE-0061": ["R", "EUDIW"],
  "MASWE-0062": ["R", "EUDIW"],
  "MASWE-0063": ["R", "EUDIW"],
  "MASWE-0064": ["R", "EUDIW"],
  "MASWE-0065": ["R", "EUDIW"],
  "MASWE-0066": ["P", "EUDIW"],
  "MASWE-0067": ["P", "EUDIW"],
  "MASWE-0068": ["P", "EUDIW"],
  "MASWE-0069": ["P", "EUDIW"],
  "MASWE-0070": ["P", "EUDIW"],
  "MASWE-0071": ["P", "EUDIW"],
  "MASWE-0072": ["P", "EUDIW"],
  "MASWE-0073": ["P", "EUDIW"],
  "MASWE-0074": ["P", "EUDIW"],
  "MASWE-0075": ["P"],
  "MASWE-0076": ["P", "EUDIW"],
  "MASWE-0077": ["P", "EUDIW"],
  "MASWE-0078": ["P", "EUDIW"],
};
/** @type {Record<string, string[]>} MASWE id → Android MASTG-TEST ids */
export const MASWE_TO_TESTS = {
  "MASWE-0001": ["MASTG-TEST-0207", "MASTG-TEST-0287", "MASTG-TEST-0304", "MASTG-TEST-0305", "MASTG-TEST-0306", "MASTG-TEST-0320"],
  "MASWE-0002": ["MASTG-TEST-0200", "MASTG-TEST-0201", "MASTG-TEST-0202"],
  "MASWE-0003": ["MASTG-TEST-0212"],
  "MASWE-0005": ["MASTG-TEST-0203", "MASTG-TEST-0231"],
  "MASWE-0006": ["MASTG-TEST-0216", "MASTG-TEST-0262"],
  "MASWE-0007": ["MASTG-TEST-0221", "MASTG-TEST-0232", "MASTG-TEST-0307", "MASTG-TEST-0308", "MASTG-TEST-0309", "MASTG-TEST-0310", "MASTG-TEST-0312", "MASTG-TEST-0350"],
  "MASWE-0012": ["MASTG-TEST-0204", "MASTG-TEST-0205"],
  "MASWE-0013": ["MASTG-TEST-0208"],
  "MASWE-0017": ["MASTG-TEST-0247", "MASTG-TEST-0249"],
  "MASWE-0018": ["MASTG-TEST-0355", "MASTG-TEST-0356", "MASTG-TEST-0357", "MASTG-TEST-0364", "MASTG-TEST-0365", "MASTG-TEST-0366"],
  "MASWE-0020": ["MASTG-TEST-0327", "MASTG-TEST-0329", "MASTG-TEST-0330"],
  "MASWE-0021": ["MASTG-TEST-0326"],
  "MASWE-0022": ["MASTG-TEST-0328"],
  "MASWE-0026": ["MASTG-TEST-0217", "MASTG-TEST-0218", "MASTG-TEST-0233", "MASTG-TEST-0235", "MASTG-TEST-0236", "MASTG-TEST-0237", "MASTG-TEST-0238", "MASTG-TEST-0239"],
  "MASWE-0027": ["MASTG-TEST-0234", "MASTG-TEST-0282", "MASTG-TEST-0283", "MASTG-TEST-0284", "MASTG-TEST-0285", "MASTG-TEST-0286", "MASTG-TEST-0295"],
  "MASWE-0028": ["MASTG-TEST-0242", "MASTG-TEST-0243", "MASTG-TEST-0244"],
  "MASWE-0029": ["MASTG-TEST-0393", "MASTG-TEST-0394"],
  "MASWE-0032": ["MASTG-TEST-0372", "MASTG-TEST-0374", "MASTG-TEST-0381"],
  "MASWE-0034": ["MASTG-TEST-0250", "MASTG-TEST-0251", "MASTG-TEST-0252", "MASTG-TEST-0253", "MASTG-TEST-0334"],
  "MASWE-0035": ["MASTG-TEST-0398", "MASTG-TEST-0399", "MASTG-TEST-0400"],
  "MASWE-0036": ["MASTG-TEST-0258", "MASTG-TEST-0316", "MASTG-TEST-0340"],
  "MASWE-0037": ["MASTG-TEST-0315"],
  "MASWE-0038": ["MASTG-TEST-0289", "MASTG-TEST-0291", "MASTG-TEST-0292", "MASTG-TEST-0293", "MASTG-TEST-0294"],
  "MASWE-0040": ["MASTG-TEST-0316"],
  "MASWE-0041": ["MASTG-TEST-0245"],
  "MASWE-0043": ["MASTG-TEST-0382", "MASTG-TEST-0392"],
  "MASWE-0044": ["MASTG-TEST-0272", "MASTG-TEST-0274"],
  "MASWE-0045": ["MASTG-TEST-0222", "MASTG-TEST-0223"],
  "MASWE-0050": ["MASTG-TEST-0337", "MASTG-TEST-0339", "MASTG-TEST-0375"],
  "MASWE-0051": ["MASTG-TEST-0324", "MASTG-TEST-0325"],
  "MASWE-0053": ["MASTG-TEST-0351"],
  "MASWE-0056": ["MASTG-TEST-0224", "MASTG-TEST-0225"],
  "MASWE-0057": ["MASTG-TEST-0338"],
  "MASWE-0058": ["MASTG-TEST-0341"],
  "MASWE-0059": ["MASTG-TEST-0368", "MASTG-TEST-0369"],
  "MASWE-0061": ["MASTG-TEST-0263", "MASTG-TEST-0264", "MASTG-TEST-0265", "MASTG-TEST-0288"],
  "MASWE-0063": ["MASTG-TEST-0226", "MASTG-TEST-0227"],
  "MASWE-0064": ["MASTG-TEST-0352", "MASTG-TEST-0353"],
  "MASWE-0066": ["MASTG-TEST-0254", "MASTG-TEST-0255", "MASTG-TEST-0256", "MASTG-TEST-0257"],
  "MASWE-0073": ["MASTG-TEST-0206", "MASTG-TEST-0318", "MASTG-TEST-0319"],
};
/** @type {Record<string, { title: string, type: string[] }>} */
export const MASTG_TEST_ANDROID = {
  "MASTG-TEST-0200": { title: "Files Written to External Storage", type: ["dynamic", "filesystem", "manual"] },
  "MASTG-TEST-0201": { title: "Runtime Use of APIs to Access External Storage", type: ["dynamic", "hooks", "manual"] },
  "MASTG-TEST-0202": { title: "References to APIs and Permissions for Accessing External Storage", type: ["static", "code", "manual"] },
  "MASTG-TEST-0203": { title: "Runtime Use of Logging APIs", type: ["dynamic", "hooks"] },
  "MASTG-TEST-0204": { title: "Insecure Random API Usage", type: ["static", "code", "manual"] },
  "MASTG-TEST-0205": { title: "Non-random Sources Usage", type: ["static", "code", "manual"] },
  "MASTG-TEST-0206": { title: "Undeclared PII in Network Traffic Capture", type: ["dynamic", "network"] },
  "MASTG-TEST-0207": { title: "Runtime Storage of Unencrypted Data in the App Sandbox", type: ["dynamic", "filesystem"] },
  "MASTG-TEST-0208": { title: "Insufficient Key Sizes", type: ["static", "code"] },
  "MASTG-TEST-0212": { title: "Use of Hardcoded Cryptographic Keys in Code", type: ["static", "code"] },
  "MASTG-TEST-0216": { title: "Sensitive Data Not Excluded From Backup", type: ["dynamic", "filesystem"] },
  "MASTG-TEST-0217": { title: "Insecure TLS Protocols Explicitly Allowed in Code", type: ["static", "code"] },
  "MASTG-TEST-0218": { title: "Insecure TLS Protocols in Network Traffic", type: ["dynamic", "network"] },
  "MASTG-TEST-0221": { title: "Broken Symmetric Encryption Algorithms", type: ["static", "code", "manual"] },
  "MASTG-TEST-0222": { title: "Position Independent Code (PIC) Not Enabled", type: ["static", "code"] },
  "MASTG-TEST-0223": { title: "Stack Canaries Not Enabled", type: ["static", "code"] },
  "MASTG-TEST-0224": { title: "Usage of Insecure APK Signature Version", type: ["static", "code"] },
  "MASTG-TEST-0225": { title: "Usage of Insecure APK Signature Key Size", type: ["static", "code"] },
  "MASTG-TEST-0226": { title: "Debuggable Flag Enabled in the AndroidManifest", type: ["static", "code"] },
  "MASTG-TEST-0227": { title: "Debugging Enabled for WebViews", type: ["static", "code"] },
  "MASTG-TEST-0231": { title: "References to Logging APIs", type: ["static", "code"] },
  "MASTG-TEST-0232": { title: "Broken Symmetric Encryption Modes", type: ["static", "code", "manual"] },
  "MASTG-TEST-0233": { title: "Hardcoded HTTP URLs", type: ["static", "code"] },
  "MASTG-TEST-0234": { title: "Missing Implementation of Server Hostname Verification with SSLSockets", type: ["static", "code"] },
  "MASTG-TEST-0235": { title: "Android App Configurations Allowing Cleartext Traffic", type: ["static", "code"] },
  "MASTG-TEST-0236": { title: "Cleartext Traffic Observed on the Network", type: ["dynamic", "network"] },
  "MASTG-TEST-0237": { title: "Cross-Platform Framework Configurations Allowing Cleartext Traffic", type: ["static", "code"] },
  "MASTG-TEST-0238": { title: "Runtime Use of Network APIs Transmitting Cleartext Traffic", type: ["dynamic", "hooks"] },
  "MASTG-TEST-0239": { title: "Using low-level APIs (e.g. Socket) to set up a custom HTTP connection", type: ["static", "code"] },
  "MASTG-TEST-0242": { title: "Missing Certificate Pinning in Network Security Configuration", type: ["static", "code"] },
  "MASTG-TEST-0243": { title: "Expired Certificate Pins in the Network Security Configuration", type: ["static", "code"] },
  "MASTG-TEST-0244": { title: "Missing Certificate Pinning in Network Traffic", type: ["dynamic", "network"] },
  "MASTG-TEST-0245": { title: "References to Platform Version APIs", type: ["static", "code"] },
  "MASTG-TEST-0247": { title: "References to APIs for Detecting Secure Screen Lock", type: ["static", "code"] },
  "MASTG-TEST-0249": { title: "Runtime Use of Secure Screen Lock Detection APIs", type: ["dynamic", "hooks"] },
  "MASTG-TEST-0250": { title: "References to Content Provider Access in WebViews", type: ["static", "code"] },
  "MASTG-TEST-0251": { title: "Runtime Use of Content Provider Access APIs in WebViews", type: ["dynamic", "hooks", "manual"] },
  "MASTG-TEST-0252": { title: "References to Local File Access in WebViews", type: ["static", "code"] },
  "MASTG-TEST-0253": { title: "Runtime Use of Local File Access APIs in WebViews", type: ["dynamic", "hooks", "manual"] },
  "MASTG-TEST-0254": { title: "Dangerous App Permissions", type: ["static", "code"] },
  "MASTG-TEST-0255": { title: "Permission Requests Not Minimized", type: [] },
  "MASTG-TEST-0256": { title: "Missing Permission Rationale", type: [] },
  "MASTG-TEST-0257": { title: "Not Resetting Unused Permissions", type: [] },
  "MASTG-TEST-0258": { title: "References to Keyboard Caching Attributes in UI Elements", type: ["static", "code"] },
  "MASTG-TEST-0262": { title: "References to Backup Configurations Not Excluding Sensitive Data", type: ["static", "code"] },
  "MASTG-TEST-0263": { title: "Logging of StrictMode Violations", type: ["dynamic", "logs"] },
  "MASTG-TEST-0264": { title: "Runtime Use of StrictMode APIs", type: ["dynamic", "hooks"] },
  "MASTG-TEST-0265": { title: "References to StrictMode APIs", type: ["static", "code"] },
  "MASTG-TEST-0272": { title: "Identify Dependencies with Known Vulnerabilities in the Android Project", type: ["static", "code"] },
  "MASTG-TEST-0274": { title: "Dependencies with Known Vulnerabilities in the App's SBOM", type: ["static", "developer"] },
  "MASTG-TEST-0282": { title: "Unsafe Custom Trust Evaluation", type: ["static", "code", "manual"] },
  "MASTG-TEST-0283": { title: "Incorrect Implementation of Server Hostname Verification", type: ["static", "code", "manual"] },
  "MASTG-TEST-0284": { title: "Incorrect SSL Error Handling in WebViews", type: ["static", "code", "manual"] },
  "MASTG-TEST-0285": { title: "Outdated Android Version Allowing Trust in User-Provided CAs", type: ["static", "code"] },
  "MASTG-TEST-0286": { title: "Network Security Configuration Allowing Trust in User-Provided CAs", type: ["static", "code"] },
  "MASTG-TEST-0287": { title: "Runtime Storage of Unencrypted Data via the SharedPreferences API", type: ["dynamic", "hooks", "manual"] },
  "MASTG-TEST-0288": { title: "Debugging Symbols in Native Binaries", type: ["static", "code"] },
  "MASTG-TEST-0289": { title: "Runtime Verification of Sensitive Content Exposure in Screenshots During App Backgrounding", type: ["dynamic", "filesystem", "manual"] },
  "MASTG-TEST-0291": { title: "References to Screen Capturing Prevention APIs", type: ["static", "code"] },
  "MASTG-TEST-0292": { title: "`setRecentsScreenshotEnabled` Not Used to Prevent Screenshots When Backgrounded", type: ["static", "code"] },
  "MASTG-TEST-0293": { title: "`setSecure` Not Used to Prevent Screenshots in SurfaceViews", type: ["static", "code"] },
  "MASTG-TEST-0294": { title: "`SecureOn` Not Used to Prevent Screenshots in Compose Dialogs", type: ["static", "code"] },
  "MASTG-TEST-0295": { title: "GMS Security Provider Not Updated", type: ["static", "code"] },
  "MASTG-TEST-0304": { title: "References to Sensitive Data Unencrypted via Android Room Database", type: ["static", "code"] },
  "MASTG-TEST-0305": { title: "Sensitive Data Stored Unencrypted via DataStore", type: ["static", "dynamic"] },
  "MASTG-TEST-0306": { title: "References to Sensitive Data Stored Unencrypted via Android Room DB", type: ["static", "code"] },
  "MASTG-TEST-0307": { title: "References to Asymmetric Key Pairs Used For Multiple Purposes", type: ["static", "code"] },
  "MASTG-TEST-0308": { title: "Runtime Use of Asymmetric Key Pairs Used For Multiple Purposes", type: ["dynamic", "hooks"] },
  "MASTG-TEST-0309": { title: "References to Reused Initialization Vectors in Symmetric Encryption", type: ["static", "code"] },
  "MASTG-TEST-0310": { title: "Runtime Use of Reused Initialization Vectors in Symmetric Encryption", type: ["dynamic", "hooks"] },
  "MASTG-TEST-0312": { title: "References to Explicit Security Provider in Cryptographic APIs", type: ["static", "code"] },
  "MASTG-TEST-0315": { title: "Sensitive Data Exposed via Notifications", type: ["static", "code"] },
  "MASTG-TEST-0316": { title: "App Exposing User Authentication Data in Text Input Fields", type: ["static", "code", "manual"] },
  "MASTG-TEST-0318": { title: "References to SDK APIs Known to Handle Sensitive User Data", type: ["static", "code"] },
  "MASTG-TEST-0319": { title: "Runtime Use of SDK APIs Known to Handle Sensitive User Data", type: ["dynamic", "hooks"] },
  "MASTG-TEST-0320": { title: "WebViews Not Cleaning Up Sensitive Data", type: ["dynamic", "hooks"] },
  "MASTG-TEST-0324": { title: "References to Root Detection Mechanisms", type: ["static", "code"] },
  "MASTG-TEST-0325": { title: "Runtime Use of Root Detection Techniques", type: ["dynamic", "hooks"] },
  "MASTG-TEST-0326": { title: "References to APIs Allowing Fallback to Non-Biometric Authentication", type: ["static", "code"] },
  "MASTG-TEST-0327": { title: "References to APIs for Event-Bound Biometric Authentication", type: ["static", "code"] },
  "MASTG-TEST-0328": { title: "References to APIs Detecting Biometric Enrollment Changes", type: ["static", "code"] },
  "MASTG-TEST-0329": { title: "References to APIs Enforcing Authentication without Explicit User Action", type: ["static", "code"] },
  "MASTG-TEST-0330": { title: "References to APIs for Keys used in Biometric Authentication with Extended Validity Duration", type: ["static", "code"] },
  "MASTG-TEST-0334": { title: "Native Code Exposed Through WebViews", type: ["static", "code", "manual"] },
  "MASTG-TEST-0337": { title: "References to Object Deserialization of Untrusted Data", type: ["static", "code"] },
  "MASTG-TEST-0338": { title: "References to Storage Integrity Check APIs", type: ["static", "code", "manual"] },
  "MASTG-TEST-0339": { title: "SQL Injection in Content Providers", type: ["static", "code"] },
  "MASTG-TEST-0340": { title: "References to Overlay Attack Protections", type: ["static", "code"] },
  "MASTG-TEST-0341": { title: "Runtime Use of Hook Detection Techniques", type: ["dynamic", "hooks"] },
  "MASTG-TEST-0350": { title: "Runtime Use of Broken Symmetric Encryption Modes", type: ["dynamic", "hooks", "manual"] },
  "MASTG-TEST-0351": { title: "Runtime Use of Emulator Detection Techniques", type: ["dynamic", "hooks"] },
  "MASTG-TEST-0352": { title: "References to Debugging Detection APIs", type: ["static", "code", "manual"] },
  "MASTG-TEST-0353": { title: "Runtime Use of Debugging Detection APIs", type: ["dynamic", "hooks", "manual"] },
  "MASTG-TEST-0355": { title: "References to Unauthorized Database Access through Content Providers", type: ["static", "config", "manual"] },
  "MASTG-TEST-0356": { title: "Runtime Verification of Unauthorized Database Access through Content Providers", type: ["dynamic", "filesystem", "manual"] },
  "MASTG-TEST-0357": { title: "References to Oversharing of File-Based Content Providers", type: ["static", "config", "code", "manual"] },
  "MASTG-TEST-0364": { title: "Exported And Unprotected Activities That Expose Sensitive Functionality", type: ["static", "config", "code", "manual"] },
  "MASTG-TEST-0365": { title: "Exported And Unprotected Services That Expose Sensitive Functionality", type: ["static", "config", "code", "manual"] },
  "MASTG-TEST-0366": { title: "Exported And Unprotected Broadcast Receivers That Expose Sensitive Functionality", type: ["static", "config", "code", "manual"] },
  "MASTG-TEST-0368": { title: "Insufficient Obfuscation of Security-Relevant Java/Kotlin Code", type: ["static", "code", "manual"] },
  "MASTG-TEST-0369": { title: "Insufficient Obfuscation of Security-Relevant Native Code", type: ["static", "package", "manual"] },
  "MASTG-TEST-0372": { title: "Implicit Intents Used for Internal App Communication", type: ["static", "code", "manual"] },
  "MASTG-TEST-0374": { title: "References to Implicit Intents Carrying Sensitive Extras", type: ["static", "code", "manual"] },
  "MASTG-TEST-0375": { title: "Missing Validation of Data Returned from Implicit Intents", type: ["dynamic", "hooks", "manual"] },
  "MASTG-TEST-0381": { title: "References to Insecure PendingIntent Creation", type: ["static"] },
  "MASTG-TEST-0382": { title: "Runtime Use of Enforced Updating APIs", type: ["dynamic", "network", "hooks", "manual"] },
  "MASTG-TEST-0392": { title: "References to Enforced Updating APIs", type: ["static", "code", "manual"] },
  "MASTG-TEST-0393": { title: "Use of Unverified App Links", type: ["static", "config"] },
  "MASTG-TEST-0394": { title: "Missing Input Validation in Custom URL Scheme Handlers", type: ["static", "code", "manual"] },
  "MASTG-TEST-0398": { title: "References to WebViewClient URL Loading Handlers", type: ["static", "code", "manual"] },
  "MASTG-TEST-0399": { title: "SafeBrowsing Disabled", type: ["static", "config", "code"] },
  "MASTG-TEST-0400": { title: "Runtime Use of WebViewClient URL Loading Handlers", type: ["dynamic", "hooks", "manual"] },
};
